# Generated by Django 3.2.12 on 2022-03-15 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220314_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=200)),
                ('peso_atual', models.FloatField()),
                ('medicacao_atual', models.TextField(blank=True)),
                ('medicacao_prescrita', models.TextField(blank=True)),
                ('exames_prescritos', models.TextField(blank=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
