# Generated by Django 3.2.12 on 2022-03-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220315_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='peso_atual',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
